# Air config for hot reload
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  full_bin = ""
  delay = 100
  exclude_dir = ["vendor", "tmp", "docs"]
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]

[log]
  time = true

[color]
  main = "cyan"
  watcher = "yellow"
  app = "green"

[misc]
  clean_on_exit = true
